### PR TITLE
Added Tests for Phase1, Checks 5 - 7

### PR DESCRIPTION
**Pull request by Madhav-S**

### CODE REVIEW

**Comment by foklepoint** [comment]
Please fix the directory name in test outputs to match with the directory of the test. Otherwise, Yuno will  recognize the tests as failing.

**Comment by Madhav-S** [comment]
Fixed, should work now (hopefully)

**Comment by foklepoint** [comment]
Almost there! Just need you to fix the file names as well. Sorry I was not clear in my previous post. Instead of file.rc, the actual file names are needed.

**Comment by Madhav-S** [comment]
Fixed the file names, didn't even notice that! Hopefully it's clean now...

**Comment by foklepoint** [comment]
Looks good! As a future reference, run the tests with yuno and see if they pass.

**Pull request merged**
